setwd("C:/Users/shuai/Documents/Shuai/jobs/en_US/finaldata/finaldata")
memory.limit(30000)
load("gram2.part1.twits.RData")
load("gram2.part1.blogs.RData")
gram2.part1.twits_blogs<-c(gram2.part1.twits,gram2.part1.blogs)
rm(gram2.part1.twits,gram2.part1.blogs)
normname<-names(gram2.part1.twits_blogs)
gram2.part1.twits_blogs<-tapply(gram2.part1.twits_blogs,normname,sum)
setwd("C:/Users/shuai/Documents/Shuai/jobs/en_US/finaldata/training")
save(gram2.part1.twits_blogs,file="gram2.part1.twits_blogs.RData")
rm(gram2.part1.twits_blogs)

setwd("C:/Users/shuai/Documents/Shuai/jobs/en_US/finaldata/finaldata")
load("gram2.part2.twits.RData")
load("gram2.part2.blogs.RData")
gram2.part2.twits_blogs<-c(gram2.part2.twits,gram2.part2.blogs)
rm(gram2.part2.twits,gram2.part2.blogs)
normname<-names(gram2.part2.twits_blogs)
gram2.part2.twits_blogs<-tapply(gram2.part2.twits_blogs,normname,sum)
setwd("C:/Users/shuai/Documents/Shuai/jobs/en_US/finaldata/training")
save(gram2.part2.twits_blogs,file="gram2.part2.twits_blogs.RData")
rm(gram2.part2.twits_blogs)

setwd("C:/Users/shuai/Documents/Shuai/jobs/en_US/finaldata/finaldata")
load("gram3.part1.twits.RData")
load("gram3.part1.blogs.RData")
gram3.part1.twits_blogs<-c(gram3.part1.twits,gram3.part1.blogs)
rm(gram3.part1.twits,gram3.part1.blogs)
normname<-names(gram3.part1.twits_blogs)
gram3.part1.twits_blogs<-tapply(gram3.part1.twits_blogs,normname,sum)
setwd("C:/Users/shuai/Documents/Shuai/jobs/en_US/finaldata/training")
save(gram3.part1.twits_blogs,file="gram3.part1.twits_blogs.RData")
rm(gram3.part1.twits_blogs)

setwd("C:/Users/shuai/Documents/Shuai/jobs/en_US/finaldata/finaldata")
load("gram3.part2.twits.RData")
load("gram3.part2.blogs.RData")
gram3.part2.twits_blogs<-c(gram3.part2.twits,gram3.part2.blogs)
rm(gram3.part2.twits,gram3.part2.blogs)
normname<-names(gram3.part2.twits_blogs)
gram3.part2.twits_blogs<-tapply(gram3.part2.twits_blogs,normname,sum)
setwd("C:/Users/shuai/Documents/Shuai/jobs/en_US/finaldata/training")
save(gram3.part2.twits_blogs,file="gram3.part2.twits_blogs.RData")
rm(gram3.part2.twits_blogs)

setwd("C:/Users/shuai/Documents/Shuai/jobs/en_US/finaldata/finaldata")
load("gram4.part1.twits.RData")
load("gram4.part1.blogs.RData")
gram4.part1.twits_blogs<-c(gram4.part1.twits,gram4.part1.blogs)
rm(gram4.part1.twits,gram4.part1.blogs)
normname<-names(gram4.part1.twits_blogs)
gram4.part1.twits_blogs<-tapply(gram4.part1.twits_blogs,normname,sum)
setwd("C:/Users/shuai/Documents/Shuai/jobs/en_US/finaldata/training")
save(gram4.part1.twits_blogs,file="gram4.part1.twits_blogs.RData")
rm(gram4.part1.twits_blogs)

setwd("C:/Users/shuai/Documents/Shuai/jobs/en_US/finaldata/finaldata")
load("gram4.part2.twits.RData")
load("gram4.part2.blogs.RData")
gram4.part2.twits_blogs<-c(gram4.part2.twits,gram4.part2.blogs)
rm(gram4.part2.twits,gram4.part2.blogs)
normname<-names(gram4.part2.twits_blogs)
gram4.part2.twits_blogs<-tapply(gram4.part2.twits_blogs,normname,sum)
setwd("C:/Users/shuai/Documents/Shuai/jobs/en_US/finaldata/training")
save(gram4.part2.twits_blogs,file="gram4.part2.twits_blogs.RData")
rm(gram4.part2.twits_blogs)

 